services:
  web:
    image: kandinsky-api
    container_name: kandinsky_api_web
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
